Added blog post "Coherence in Rust (feat. rustc sources)"
A blog post about the error

```
error[E0210]: type parameter `T` must be covered by another type when it appears before the first local type
```

with code for causing this error, rational for coherence rules and code in `rustc` for checking the rules and generating the error (long!)