fix python urllib syntax
After upgrading to Ubuntu 22.04 with Python 3.10.6, the script crashes
with
    AttributeError: module 'urllib' has no attribute 'parse'

Apparently the import was wrong all along, but some quirk of the older
system allowed it to work previously.